#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HealthyAppAI.Resource", IsApplication=true)]

namespace HealthyAppAI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DSoft.UI.Resource.Drawable.checkmark = global::HealthyAppAI.Resource.Drawable.checkmark;
			global::DSoft.UI.Resource.String.library_name = global::HealthyAppAI.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int provinces_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_home = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int checkmark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IconHealthy = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06005d
			public const int btnClear = 2131099741;
			
			// aapt resource value: 0x7f0600a2
			public const int btnHome = 2131099810;
			
			// aapt resource value: 0x7f0600a3
			public const int btnHomeTres = 2131099811;
			
			// aapt resource value: 0x7f0600a6
			public const int btnNext = 2131099814;
			
			// aapt resource value: 0x7f0600a5
			public const int btnPrevious = 2131099813;
			
			// aapt resource value: 0x7f06005c
			public const int checkReadRealease = 2131099740;
			
			// aapt resource value: 0x7f060005
			public const int dropProvince = 2131099653;
			
			// aapt resource value: 0x7f0600a4
			public const int fragmentContainer = 2131099812;
			
			// aapt resource value: 0x7f06000c
			public const int interested = 2131099660;
			
			// aapt resource value: 0x7f06005e
			public const int myDataGrid = 2131099742;
			
			// aapt resource value: 0x7f060019
			public const int radioAcne = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int radioAcneNo = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int radioAcneYes = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int radioAllergies = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int radioAllergiesNo = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int radioAllergiesYes = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int radioAlz = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int radioAlzNo = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int radioAlzYes = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int radioArt = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int radioArtNo = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int radioArtYes = 2131099683;
			
			// aapt resource value: 0x7f060016
			public const int radioCancer = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int radioCancerNo = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int radioCancerYes = 2131099671;
			
			// aapt resource value: 0x7f06002b
			public const int radioChronic = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int radioChronicNo = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int radioChronicYes = 2131099692;
			
			// aapt resource value: 0x7f060025
			public const int radioCircadian = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int radioCircadianNo = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int radioCircadianYes = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int radioCirculation = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int radioCirculationNo = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int radioCirculationYes = 2131099689;
			
			// aapt resource value: 0x7f060031
			public const int radioDepression = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int radioDepressionNo = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int radioDepressionYes = 2131099698;
			
			// aapt resource value: 0x7f06002e
			public const int radioDerma = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int radioDermaNo = 2131099696;
			
			// aapt resource value: 0x7f06002f
			public const int radioDermaYes = 2131099695;
			
			// aapt resource value: 0x7f060034
			public const int radioDiabetes = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int radioDiabetesNo = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int radioDiabetesYes = 2131099701;
			
			// aapt resource value: 0x7f06009a
			public const int radioDistributor = 2131099802;
			
			// aapt resource value: 0x7f06009c
			public const int radioDistributorNo = 2131099804;
			
			// aapt resource value: 0x7f06009b
			public const int radioDistributorYes = 2131099803;
			
			// aapt resource value: 0x7f060097
			public const int radioEducation = 2131099799;
			
			// aapt resource value: 0x7f060099
			public const int radioEducationNo = 2131099801;
			
			// aapt resource value: 0x7f060098
			public const int radioEducationYes = 2131099800;
			
			// aapt resource value: 0x7f060067
			public const int radioEnergized = 2131099751;
			
			// aapt resource value: 0x7f06006a
			public const int radioEnergizedNeutral = 2131099754;
			
			// aapt resource value: 0x7f060069
			public const int radioEnergizedNo = 2131099753;
			
			// aapt resource value: 0x7f060068
			public const int radioEnergizedYes = 2131099752;
			
			// aapt resource value: 0x7f060081
			public const int radioFamiliy = 2131099777;
			
			// aapt resource value: 0x7f060083
			public const int radioFamiliyNo = 2131099779;
			
			// aapt resource value: 0x7f060082
			public const int radioFamiliyYes = 2131099778;
			
			// aapt resource value: 0x7f060037
			public const int radioFibro = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int radioFibroNo = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int radioFibroYes = 2131099704;
			
			// aapt resource value: 0x7f060091
			public const int radioFinancing = 2131099793;
			
			// aapt resource value: 0x7f060093
			public const int radioFinancingNo = 2131099795;
			
			// aapt resource value: 0x7f060092
			public const int radioFinancingYes = 2131099794;
			
			// aapt resource value: 0x7f06003a
			public const int radioHair = 2131099706;
			
			// aapt resource value: 0x7f06003c
			public const int radioHairNo = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int radioHairYes = 2131099707;
			
			// aapt resource value: 0x7f06006f
			public const int radioHappier = 2131099759;
			
			// aapt resource value: 0x7f060072
			public const int radioHappierNeutral = 2131099762;
			
			// aapt resource value: 0x7f060071
			public const int radioHappierNo = 2131099761;
			
			// aapt resource value: 0x7f060070
			public const int radioHappierYes = 2131099760;
			
			// aapt resource value: 0x7f06008e
			public const int radioHost = 2131099790;
			
			// aapt resource value: 0x7f060090
			public const int radioHostNo = 2131099792;
			
			// aapt resource value: 0x7f06008f
			public const int radioHostYes = 2131099791;
			
			// aapt resource value: 0x7f06008b
			public const int radioIntroduceLight = 2131099787;
			
			// aapt resource value: 0x7f06008d
			public const int radioIntroduceLightNo = 2131099789;
			
			// aapt resource value: 0x7f06008c
			public const int radioIntroduceLightYes = 2131099788;
			
			// aapt resource value: 0x7f06007d
			public const int radioKnowMore = 2131099773;
			
			// aapt resource value: 0x7f06007f
			public const int radioKnowMoreNo = 2131099775;
			
			// aapt resource value: 0x7f06007e
			public const int radioKnowMoreYes = 2131099774;
			
			// aapt resource value: 0x7f060013
			public const int radioLight = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int radioLightNo = 2131099669;
			
			// aapt resource value: 0x7f06009d
			public const int radioLightParties = 2131099805;
			
			// aapt resource value: 0x7f06009f
			public const int radioLightPartiesNo = 2131099807;
			
			// aapt resource value: 0x7f06009e
			public const int radioLightPartiesYes = 2131099806;
			
			// aapt resource value: 0x7f060014
			public const int radioLightYes = 2131099668;
			
			// aapt resource value: 0x7f06006b
			public const int radioLighter = 2131099755;
			
			// aapt resource value: 0x7f06006e
			public const int radioLighterNeutral = 2131099758;
			
			// aapt resource value: 0x7f06006d
			public const int radioLighterNo = 2131099757;
			
			// aapt resource value: 0x7f06006c
			public const int radioLighterYes = 2131099756;
			
			// aapt resource value: 0x7f06003d
			public const int radioNerve = 2131099709;
			
			// aapt resource value: 0x7f06003f
			public const int radioNerveNo = 2131099711;
			
			// aapt resource value: 0x7f06003e
			public const int radioNerveYes = 2131099710;
			
			// aapt resource value: 0x7f06000e
			public const int radioNo = 2131099662;
			
			// aapt resource value: 0x7f060085
			public const int radioOwnLight = 2131099781;
			
			// aapt resource value: 0x7f060087
			public const int radioOwnLightNo = 2131099783;
			
			// aapt resource value: 0x7f060086
			public const int radioOwnLightYes = 2131099782;
			
			// aapt resource value: 0x7f060063
			public const int radioPain = 2131099747;
			
			// aapt resource value: 0x7f060066
			public const int radioPainNeutral = 2131099750;
			
			// aapt resource value: 0x7f060065
			public const int radioPainNo = 2131099749;
			
			// aapt resource value: 0x7f060064
			public const int radioPainYes = 2131099748;
			
			// aapt resource value: 0x7f060049
			public const int radioPhysical = 2131099721;
			
			// aapt resource value: 0x7f06004b
			public const int radioPhysicalNo = 2131099723;
			
			// aapt resource value: 0x7f06004a
			public const int radioPhysicalYes = 2131099722;
			
			// aapt resource value: 0x7f060010
			public const int radioPregnant = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int radioPregnantNo = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int radioPregnantYes = 2131099665;
			
			// aapt resource value: 0x7f06005f
			public const int radioRelaxed = 2131099743;
			
			// aapt resource value: 0x7f060062
			public const int radioRelaxedNeutral = 2131099746;
			
			// aapt resource value: 0x7f060061
			public const int radioRelaxedNo = 2131099745;
			
			// aapt resource value: 0x7f060060
			public const int radioRelaxedYes = 2131099744;
			
			// aapt resource value: 0x7f060088
			public const int radioRentLight = 2131099784;
			
			// aapt resource value: 0x7f06008a
			public const int radioRentLightNo = 2131099786;
			
			// aapt resource value: 0x7f060089
			public const int radioRentLightYes = 2131099785;
			
			// aapt resource value: 0x7f060079
			public const int radioSessions = 2131099769;
			
			// aapt resource value: 0x7f06007b
			public const int radioSessionsNo = 2131099771;
			
			// aapt resource value: 0x7f06007a
			public const int radioSessionsYes = 2131099770;
			
			// aapt resource value: 0x7f06004c
			public const int radioSkin = 2131099724;
			
			// aapt resource value: 0x7f06004e
			public const int radioSkinNo = 2131099726;
			
			// aapt resource value: 0x7f06004d
			public const int radioSkinYes = 2131099725;
			
			// aapt resource value: 0x7f060040
			public const int radioStroke = 2131099712;
			
			// aapt resource value: 0x7f060042
			public const int radioStrokeNo = 2131099714;
			
			// aapt resource value: 0x7f060041
			public const int radioStrokeYes = 2131099713;
			
			// aapt resource value: 0x7f060094
			public const int radioSupport = 2131099796;
			
			// aapt resource value: 0x7f060096
			public const int radioSupportNo = 2131099798;
			
			// aapt resource value: 0x7f060095
			public const int radioSupportYes = 2131099797;
			
			// aapt resource value: 0x7f060073
			public const int radioSympthons = 2131099763;
			
			// aapt resource value: 0x7f060076
			public const int radioSympthonsNeutral = 2131099766;
			
			// aapt resource value: 0x7f060075
			public const int radioSympthonsNo = 2131099765;
			
			// aapt resource value: 0x7f060074
			public const int radioSympthonsYes = 2131099764;
			
			// aapt resource value: 0x7f060043
			public const int radioTBI = 2131099715;
			
			// aapt resource value: 0x7f060045
			public const int radioTBINo = 2131099717;
			
			// aapt resource value: 0x7f060044
			public const int radioTBIYes = 2131099716;
			
			// aapt resource value: 0x7f060046
			public const int radioThyroid = 2131099718;
			
			// aapt resource value: 0x7f060048
			public const int radioThyroidNo = 2131099720;
			
			// aapt resource value: 0x7f060047
			public const int radioThyroidYes = 2131099719;
			
			// aapt resource value: 0x7f06004f
			public const int radioWeight = 2131099727;
			
			// aapt resource value: 0x7f060051
			public const int radioWeightNo = 2131099729;
			
			// aapt resource value: 0x7f060050
			public const int radioWeightYes = 2131099728;
			
			// aapt resource value: 0x7f060052
			public const int radioWound = 2131099730;
			
			// aapt resource value: 0x7f060054
			public const int radioWoundNo = 2131099732;
			
			// aapt resource value: 0x7f060053
			public const int radioWoundYes = 2131099731;
			
			// aapt resource value: 0x7f06000d
			public const int radioYes = 2131099661;
			
			// aapt resource value: 0x7f06005a
			public const int signatureProspect = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int signatureWitness = 2131099739;
			
			// aapt resource value: 0x7f06000b
			public const int textView = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int txtCity = 2131099651;
			
			// aapt resource value: 0x7f060055
			public const int txtConcern1 = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int txtConcern2 = 2131099734;
			
			// aapt resource value: 0x7f06000a
			public const int txtEmail = 2131099658;
			
			// aapt resource value: 0x7f060080
			public const int txtEmailKnow = 2131099776;
			
			// aapt resource value: 0x7f060078
			public const int txtExperienceComments = 2131099768;
			
			// aapt resource value: 0x7f060077
			public const int txtExperienceOther = 2131099767;
			
			// aapt resource value: 0x7f060084
			public const int txtFamily = 2131099780;
			
			// aapt resource value: 0x7f060000
			public const int txtFirstName = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int txtHomePhone = 2131099655;
			
			// aapt resource value: 0x7f060058
			public const int txtInitials = 2131099736;
			
			// aapt resource value: 0x7f060001
			public const int txtLastName = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int txtMobile = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int txtPostalCode = 2131099654;
			
			// aapt resource value: 0x7f06007c
			public const int txtPreferredCity = 2131099772;
			
			// aapt resource value: 0x7f060057
			public const int txtPrintName = 2131099735;
			
			// aapt resource value: 0x7f060002
			public const int txtProfession = 2131099650;
			
			// aapt resource value: 0x7f0600a1
			public const int txtQuestionsComments = 2131099809;
			
			// aapt resource value: 0x7f0600a0
			public const int txtQuestionsOther = 2131099808;
			
			// aapt resource value: 0x7f060004
			public const int txtStreet = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int txtTakingMed = 2131099663;
			
			// aapt resource value: 0x7f060059
			public const int txtWitnessName = 2131099737;
			
			// aapt resource value: 0x7f060008
			public const int txtWorkPhone = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ApplicationStep1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ApplicationStep2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ApplicationStep3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ApplicationStep4 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FeedbackList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FeedbackStep1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FeedbackStep2 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FeedbackStep3 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TabContainer = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04001c
			public const int acne = 2130968604;
			
			// aapt resource value: 0x7f04004d
			public const int additional_questions = 2130968653;
			
			// aapt resource value: 0x7f04001d
			public const int allergies = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int alzheimer = 2130968606;
			
			// aapt resource value: 0x7f040017
			public const int are_you = 2130968599;
			
			// aapt resource value: 0x7f04001f
			public const int arthritis = 2130968607;
			
			// aapt resource value: 0x7f04001a
			public const int cancer = 2130968602;
			
			// aapt resource value: 0x7f040022
			public const int chronic = 2130968610;
			
			// aapt resource value: 0x7f040020
			public const int circadian = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int circulation = 2130968609;
			
			// aapt resource value: 0x7f04003b
			public const int comment_experience = 2130968635;
			
			// aapt resource value: 0x7f040024
			public const int depression = 2130968612;
			
			// aapt resource value: 0x7f040023
			public const int dermatological = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int diabetes = 2130968613;
			
			// aapt resource value: 0x7f040051
			public const int distributorship = 2130968657;
			
			// aapt resource value: 0x7f040050
			public const int education = 2130968656;
			
			// aapt resource value: 0x7f04003e
			public const int energized = 2130968638;
			
			// aapt resource value: 0x7f040053
			public const int external_dir = 2130968659;
			
			// aapt resource value: 0x7f040026
			public const int fibro = 2130968614;
			
			// aapt resource value: 0x7f04004e
			public const int financing = 2130968654;
			
			// aapt resource value: 0x7f040044
			public const int further_sessions = 2130968644;
			
			// aapt resource value: 0x7f040027
			public const int hair = 2130968615;
			
			// aapt resource value: 0x7f040040
			public const int happier = 2130968640;
			
			// aapt resource value: 0x7f040047
			public const int have_family = 2130968647;
			
			// aapt resource value: 0x7f040016
			public const int help_us = 2130968598;
			
			// aapt resource value: 0x7f04000a
			public const int hint_city = 2130968586;
			
			// aapt resource value: 0x7f040043
			public const int hint_comments = 2130968643;
			
			// aapt resource value: 0x7f040005
			public const int hint_firstname = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int hint_homephone = 2130968589;
			
			// aapt resource value: 0x7f040037
			public const int hint_initial = 2130968631;
			
			// aapt resource value: 0x7f040006
			public const int hint_lastname = 2130968582;
			
			// aapt resource value: 0x7f040010
			public const int hint_mail = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int hint_mobile = 2130968591;
			
			// aapt resource value: 0x7f040042
			public const int hint_other = 2130968642;
			
			// aapt resource value: 0x7f04000c
			public const int hint_postalcode = 2130968588;
			
			// aapt resource value: 0x7f040045
			public const int hint_preferred_city = 2130968645;
			
			// aapt resource value: 0x7f040036
			public const int hint_printname = 2130968630;
			
			// aapt resource value: 0x7f040007
			public const int hint_profession = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int hint_provinces = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int hint_street = 2130968585;
			
			// aapt resource value: 0x7f040032
			public const int hint_top1 = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hint_top2 = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hint_top3 = 2130968628;
			
			// aapt resource value: 0x7f040038
			public const int hint_witnessname = 2130968632;
			
			// aapt resource value: 0x7f04000e
			public const int hint_workphone = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int home_button = 2130968578;
			
			// aapt resource value: 0x7f04004c
			public const int host_presentation = 2130968652;
			
			// aapt resource value: 0x7f04002c
			public const int interested = 2130968620;
			
			// aapt resource value: 0x7f04004b
			public const int introduce_light = 2130968651;
			
			// aapt resource value: 0x7f040046
			public const int know_more = 2130968646;
			
			// aapt resource value: 0x7f040054
			public const int library_name = 2130968660;
			
			// aapt resource value: 0x7f040052
			public const int light_parties = 2130968658;
			
			// aapt resource value: 0x7f040019
			public const int light_sensitive = 2130968601;
			
			// aapt resource value: 0x7f04003f
			public const int lighter = 2130968639;
			
			// aapt resource value: 0x7f040048
			public const int love_idea = 2130968648;
			
			// aapt resource value: 0x7f040028
			public const int nerve = 2130968616;
			
			// aapt resource value: 0x7f040004
			public const int next_button = 2130968580;
			
			// aapt resource value: 0x7f040049
			public const int own_light = 2130968649;
			
			// aapt resource value: 0x7f04003d
			public const int pain = 2130968637;
			
			// aapt resource value: 0x7f04002d
			public const int physical = 2130968621;
			
			// aapt resource value: 0x7f040018
			public const int pregnant = 2130968600;
			
			// aapt resource value: 0x7f040003
			public const int prev_button = 2130968579;
			
			// aapt resource value: 0x7f040014
			public const int radio_neutral = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int radio_no = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int radio_yes = 2130968594;
			
			// aapt resource value: 0x7f04003a
			public const int read_release = 2130968634;
			
			// aapt resource value: 0x7f040035
			public const int read_waiver = 2130968629;
			
			// aapt resource value: 0x7f040011
			public const int receive_mail = 2130968593;
			
			// aapt resource value: 0x7f04003c
			public const int relaxed = 2130968636;
			
			// aapt resource value: 0x7f04004a
			public const int rent_light = 2130968650;
			
			// aapt resource value: 0x7f04002e
			public const int skin = 2130968622;
			
			// aapt resource value: 0x7f040029
			public const int stroke = 2130968617;
			
			// aapt resource value: 0x7f04004f
			public const int support = 2130968655;
			
			// aapt resource value: 0x7f040041
			public const int sympthons = 2130968641;
			
			// aapt resource value: 0x7f040015
			public const int taking_med = 2130968597;
			
			// aapt resource value: 0x7f04002a
			public const int tbi = 2130968618;
			
			// aapt resource value: 0x7f040039
			public const int thank_you_app = 2130968633;
			
			// aapt resource value: 0x7f04002b
			public const int thyroid = 2130968619;
			
			// aapt resource value: 0x7f040008
			public const int title_activity_application = 2130968584;
			
			// aapt resource value: 0x7f040031
			public const int top_areas = 2130968625;
			
			// aapt resource value: 0x7f04002f
			public const int weight_loss = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int wound = 2130968624;
			
			// aapt resource value: 0x7f04001b
			public const int you_have = 2130968603;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
